name: smart_knee
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Estado
  flutter_riverpod: ^2.5.0

  # BLE central (versi√≥n compatible con Flutter actual)
  flutter_reactive_ble: ^5.4.0

  # Permisos en runtime
  permission_handler: ^11.3.0

  # Base de datos local
  drift: ^2.18.0
  drift_sqflite: ^2.0.0
  path_provider: ^2.1.4

  # Utilidades
  intl: ^0.19.0

dev_dependencies:
  drift_dev: ^2.18.0
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
